version: '3.8'

services:
  # --- Catalog Service ---
  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - catalog-db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    restart: always
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./catalog-service:/var/www/html
    ports:
      - "8001:8000"
    depends_on:
      - catalog-db

  # --- Checkout Service ---
  checkout-db:
    image: mysql:8.0
    container_name: checkout-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checkout
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - checkout-db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  checkout-service:
    build: ./checkout-service
    container_name: checkout-service
    restart: always
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./checkout-service:/var/www/html
    ports:
      - "8002:8000"
    depends_on:
      - checkout-db
      - catalog-service
      - email-service

  # --- Email Service ---
  email-service:
    build: ./email-service
    container_name: email-service
    restart: always
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./email-service:/var/www/html
    ports:
      - "8003:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - catalog-service
      - checkout-service
      - email-service

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP port (used by Laravel)
      - "8025:8025" # Web UI port



volumes:
  catalog-db-data:
  checkout-db-data:
